### ISSUE TITLE
Question: How to upload add attachments>

### ISSUE THREAD

**Issue by cyrillkalita** [MacsiDigital/laravel-api-client#13]
- API Version: 3.3.5
- Laravel Version: 8.44.1
- PHP Version: 7.4

Perhaps a silly question, but I cannot figure out a way to seamlessly upload files within a single request.

Assuming my Entry is:
```php
    return Client::baseUrl($url)>accept('application/json')->withToken($token);
```

how can I pass values to the APIResource to have it accept multiple files?

```php
$this->query()->attachFile('attachments', File::get($path), File::basename($path));
```

**Comment by colinhall17** [comment]
Hi @cyrillkalita 

Apologies in the delay in getting back to you.  I implemented it on the zoom library as below

return $this->newQuery()->attachFile('pic_file', file_get_contents($image), $image)->sendRequest('post', ['users/'.$this->id.'/picture'])->successful();

The attach file function will just add it as a variable ready for the request, then you need to call the request to the correct endpoint.  The successful call will just return a bool depending on if successful.

Hope that helps
