### ISSUE TITLE
Is it possible to mock the HTTP responses for testing?

### ISSUE THREAD

**Issue by SuperDJ** [MacsiDigital/laravel-api-client#14]
As the title states, is it possible to mock the HTTP responses for testing?

It would be nice if we could use Laravel's build in [HTTP client](https://laravel.com/docs/8.x/http-client). It would make mocking responses and testing a breeze.

**Comment by colinhall17** [comment]
Hi

The Client class does extend the HTTP Client under the hood, so it should be possible to use response mocking.
