### ISSUE TITLE
Question about relations

### ISSUE THREAD

**Issue by agnonym** [MacsiDigital/laravel-api-client#15]
Hi,
first of all I'd like to thank you all for this package as I have to build a Laravel project that consumes a Laravel API (through Apiato package), and it made me save big time.

I added a with() method on my Builder class to use eager loading on the API side, and if I call my relation on my Resource model, it works well and give me a Collection (for a HasMany) of related Resource (just had to override the HasMany hydate() method as each relation is also in a `data` array).

My problem is I use the data in an Inertia (Vue.js) frontend, so I use the toArray() method to convert my object, and as the relations are not automatically loaded (because they are not called, and Laravel relationsToArray() returns nothing as the relations property is empty), so they are empty in my array.

I don't think it's a bug and I know that's not a standard behavior handled by this package, but I'm looking for the best way to have my relations automatically loaded after API calls (in the populate() method of the Resultset class for get calls and in the processIndividualResponse() method of the Builder class for find calls).
If someone had to deal with this kind of usecase, do you know if there is some methods in the package that I can use to do so?

**Sample data from the API**
```
{
    "data": [
        {
            "object": "ClientUser",
            "id": "L9weVlmdVO14Xrab",
            "username": "super-client",
            "email": "admin@client.com",
            "firstname": "client",
            "lastname": "super",
            "created_at": "2022-03-08T17:36:52.000000Z",
            "updated_at": "2022-03-08T17:36:52.000000Z",
            "clients": {
                "data": [
                    {
                        "object": "Client",
                        "id": "L9weVlmdVO14Xrab",
                        "code": "AAA",
                        "created_at": "2022-03-13T16:43:27.000000Z",
                        "updated_at": "2022-03-13T16:43:27.000000Z"
                    }
                ]
            }
        }
    ],
    "meta": {
        "include": [
            "clients",
            "user_classes"
        ],
        "custom": [],
        "pagination": {
            "total": 1,
            "count": 1,
            "per_page": 10,
            "current_page": 1,
            "total_pages": 1,
            "links": {}
        }
    }
}
```

**Comment by colinhall17** [comment]
From memory I think the package would try to eager load relationships and you could select which ones to lazy load, but it caused an issue, so I had to remove it.

The package is long overdue a rewrite and the ability to eager or lazy load would be good, but I can't guarantee any timescales at the minute

**Comment by agnonym** [comment]
Hi,
In the end, I overrided many functions in the ApiResource, Builder and Resultset to adapt the behavior to the project (like adding a function to populate the relations when needed, but it surely won't fit to other users).
Thanks again for this package that gives a good starter kit to use API quite as Eloquent models!!
