### ISSUE TITLE
Cannot install macsidigital/laravel-zoom

### ISSUE THREAD

**Issue by PasanBhanu** [MacsiDigital/laravel-api-client#5]
Installation failed due to guzzlehttp/guzzle version conflict. 

My guzzle version : **"guzzlehttp/guzzle": "^7.0",**
Please update your composer to allow ^7.0

Problem 1
    - Conclusion: remove guzzlehttp/guzzle 7.0.1
    - Conclusion: don't install guzzlehttp/guzzle 7.0.1
    - macsidigital/laravel-zoom 4.0.0 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.1 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.2 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.3 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.4 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.5 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.6 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.7 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.8 requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].    - macsidigital/laravel-zoom 4.0.x-dev requires macsidigital/laravel-api-client ^3.0 -> satisfiable by macsidigital/laravel-api-client[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.x-dev].
    - macsidigital/laravel-api-client 3.0.0 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.1 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.2 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.3 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.4 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.5 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.6 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.7 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.8 requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - macsidigital/laravel-api-client 3.0.x-dev requires guzzlehttp/guzzle ~6.0|~5.0|~4.0 -> satisfiable by guzzlehttp/guzzle[4.x-dev, 5.3.x-dev, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[4.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[5.3.x-dev, 7.0.1].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0) -> satisfiable by guzzlehttp/guzzle[7.0.1].
    - Installation request for macsidigital/laravel-zoom ^4.0 -> satisfiable by macsidigital/laravel-zoom[4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.x-dev].

**Comment by colinhall17** [comment]
Hi @PasanBhanu 

Thanks for getting in touch, we have bumped all versions to Guzzle 7.  You can use 3.1, 2.1 or 1.1 of the API library for bumped version
