### ISSUE TITLE
Error when recurrences is empty

### ISSUE THREAD

**Issue by cheshirec7** [MacsiDigital/laravel-api-client#7]
Getting this error when there are no occurrences for a recurring meeting:
Invalid argument supplied for foreach() {"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /home/vagrant/code/homestead/vendor/macsidigital/laravel-api-client/src/Support/ResultSet.php:122)

The problem occurs because $response->json() is empty:
 protected function processResponse($response)
    {
        $this->addResponse($response);
        $this->populate($response->json());
        $this->processMeta($response->json());
        $this->incrementQueries();
    }

My code:
$meetings = Zoom::user()->find($email)->meetings;
        foreach ($meetings as $meeting) {
            if ($meeting->type == 8) {
                $meet = $meeting->find($meeting->id);
                    foreach ($meet->occurrences as $occ) {
etc.

**Comment by colinhall17** [comment]
Hi @cheshirec7 

Can you please reply with which version of zoom / the api-client you are using.

Thanks

**Comment by cheshirec7** [comment]
Hi -

I keep up with the latest everything by running
  php -d memory_limit=-1 `which composer` update
every day.

[image: require.jpg]

**Comment by colinhall17** [comment]
We have 3 different versions depending on which version of Laravel you use.

I think I have spotted the issue and patched it, can you try now and let me know if it is still an issue.

**Comment by cheshirec7** [comment]
Ah, sorry, I didn't realize there were three versions. I know how annoying
it is when someone doesn't give all the needed info.

Got the latest and it works. Thanks!
